AWSTemplateFormatVersion: "2010-09-09"
Description: create a role assum 
Parameters:
  BucketName:
    Type: String
    Default: "ex-chester-237"
Resources:
  S3bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
  StsRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::038462793211:user/sts-machine-user"
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: '*'
                Resource: [
                  !Sub "arn:aws:s3:::*",
                  !Sub "arn:aws:s3:::${BucketName}",
                  !Sub "arn:aws:s3:::${BucketName}/*"
                ]