#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
    echo "No prefix resource name"
    exit 1
fi

PREFIX=$1

# create VPC
VPC_ID=$(aws ec2 create-vpc \
--cidr-block "172.1.0.0/16" \
--region ap-southeast-1 \
--tag-specifications "ResourceType=vpc, Tags=[{Key=Name, Value=$PREFIX-vpc}]" \
--query Vpc.VpcId \
--output text)

echo $VPC_ID

# Modify VPC
aws ec2 modify-vpc-attribute \
--vpc-id $VPC_ID \
--enable-dns-hostname

# create IGW
IGW_ID=$(aws ec2 create-internet-gateway \
--tag-specifications "ResourceType=internet-gateway, Tags=[{Key=Name, Value=$PREFIX-igw}]" \
--query InternetGateway.InternetGatewayId \
--output text)

echo $IGW_ID

# attach IGW
aws ec2 attach-internet-gateway \
--internet-gateway-id $IGW_ID \
--vpc-id $VPC_ID

# create subnets
SUBNET_ID1=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block "172.1.0.0/24" \
--tag-specifications "ResourceType=subnet, Tags=[{Key=Name, Value=$PREFIX-subnet-01}]" \
--query Subnet.SubnetId \
--output text)

aws ec2 modify-subnet-attribute \
--subnet-id $SUBNET_ID1 \
--map-public-ip-on-launch

echo $SUBNET_ID1


SUBNET_ID2=$(aws ec2 create-subnet \
--vpc-id $VPC_ID \
--cidr-block "172.1.1.0/24" \
--tag-specifications "ResourceType=subnet, Tags=[{Key=Name, Value=$PREFIX-subnet-02}]" \
--query Subnet.SubnetId \
--output text)

aws ec2 modify-subnet-attribute \
--subnet-id $SUBNET_ID2 \
--map-public-ip-on-launch

echo $SUBNET_ID2

# Route table associate to subnets
# default route table is created auto on VPC creation
RT_ID=$(aws ec2 describe-route-tables \
--filter "Name=vpc-id,Values=$VPC_ID" "Name=association.main,Values=true" \
--query RouteTables[].RouteTableId \
--output text)

echo $RT_ID

aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID1

aws ec2 associate-route-table \
--route-table-id $RT_ID \
--subnet-id $SUBNET_ID2

# create route from route table to IGW
aws ec2 create-route \
--route-table-id $RT_ID \
--gateway-id $IGW_ID \
--destination-cidr-block "0.0.0.0/0"

