#!/usr/bin/env bash

echo "Create bucket"

if [ -z "$1" ]; then
    echo "No bucket name"
    exit 1
fi

BUCKET_NAME=$1

aws s3api create-bucket \
--bucket $BUCKET_NAME \
--create-bucket-configuration="LocationConstraint=ap-southeast-1" \
--query Location \
--output text