#!/usr/bin/env bash 
echo ">> Put objects"
set -e

OUTPUT_FOLDER="../temp"

rm -r $OUTPUT_FOLDER

mkdir -p $OUTPUT_FOLDER

for((i=1; i<=10; i++)); do
    FILENAME="$OUTPUT_FOLDER/file_$i.txt"
    dd if=/dev/urandom of=$FILENAME bs=1024 count=1 2>/dev/null
done

tree $OUTPUT_FOLDER