#!/usr/bin/env bash

set -e

echo ">>Sync"

if [ -z "$1" ]; then
    echo "No bucket name"
    exit 1
fi
BUCKET_NAME=$1

if [ -z "$2" ]; then
    echo "No file prefix"
    exit 1
fi
FILE_PREFIX=$2

OUTPUT_FOLDER="../temp"

rm -r $OUTPUT_FOLDER

mkdir -p $OUTPUT_FOLDER

for((i=1; i<=10; i++)); do
    FILENAME="$OUTPUT_FOLDER/file_$i.txt"
    dd if=/dev/urandom of=$FILENAME bs=1024 count=1 2>/dev/null
done

aws s3 sync $OUTPUT_FOLDER s3://$BUCKET_NAME/$FILE_PREFIX