#!/usr/bin/env bash

echo ">> Deploy S3 bucket by CFN"

STACK_NAME="cfn-s3-simple"

aws cloudformation deploy \
--template-file template.yaml \
--region ap-southeast-1 \
--stack-name $STACK_NAME \
--no-execute-changeset