#!/usr/bin/env bash

echo ">> Deploy EC2 instance by CFN"

STACK_NAME="cfn-EC2-example"

aws cloudformation deploy \
--template-file template.yaml \
--region ap-southeast-1 \
--stack-name $STACK_NAME \
--capabilities CAPABILITY_IAM \
--parameter-overrides UserData="$(< userdata.yml)"
# --no-execute-changeset \