#cloud-config

package_update: true
package_upgrade: true
packages:
  - httpd

write_files:
  - path: /var/www/html/index.html
    content:
      <h1>This is Chester's site running on EC2</h1>
    owner: root:root
    permission: '0644'

runcmd:
  - systemctl start httpd.service
  - systemctl enable httpd.service
  - systemctl restart httpd.service